### ISSUE TITLE
Copy to clipboard button.

### ISSUE THREAD

**Issue by patelvivekdev** [mwskwong/mwskwong.com-archive#371]
Hi Matthew,

Your portfolio looks fantastic.

I noticed that the copy button is positioned above the text on mobile devices.

![image](https://github.com/mwskwong/mwskwong.com/assets/43227010/c47c6ef5-c375-4a29-a118-0172749e33b2)

Was this intentional, or is it an issue?

**Comment by mwskwong** [comment]
That's intentional. I made sure I left enough space to not cover any content when users scroll to the far right.
![image](https://github.com/mwskwong/mwskwong.com/assets/32725014/3544a7a0-677e-4bb2-8de9-56828315e0fd)
